anfisa/urls.py
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path 

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    # Сначала проверяем все пути, которые есть в приложении ice_cream
    path('', include('ice_cream.urls', namespace='ice_cream')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path
from . import views

# Эта строчка обязательна. 
# Без нее чуда не произойдет и namespace работать не будет
app_name = 'feedback'

urlpatterns = [
    # Главная страница
    path('', views.index, name='feedback_list'),
    path('publish-feedback/', views.publish_feedback, name='publish_feedback'),
    path('publish-feedback/publish/', views.feedback, name='feedback_success'),

]

ice_cream/urls.py
from django.urls import path
from . import views

# Эта строчка обязательна. 
# Без нее чуда не произойдет и namespace работать не будет
app_name = 'ice_cream'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Список мороженого
    path('ice_cream/', views.ice_cream_list, name='ice_cream_list'),
    # Подробная информация о мороженом. Ждем пременную типа int, 
    # и будем использовать ее под именем pk
    path('ice_cream/<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

feedback/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.
class FeedBack(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='feedbacks', verbose_name='Автор')
    email = models.EmailField(verbose_name='Почта')
    message = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.author} отзыв'
    
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
    

ice_cream/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill


class IceCream(models.Model):
    name = models.CharField('Название', max_length=200)
    description = models.TextField('Описание')
    on_main = models.BooleanField('На главную?', default=True)

    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)

    class Meta:        
        ordering = ('name',)
        verbose_name = 'мороженое'
        verbose_name_plural = 'мороженое'

    def __str__(self):
        return f'{self.name}'
    

    def get_first_image(self):
        if self.images:
            return self.images.first().image.url
        else:
            return 

    def get_first_thumbnail(self):
        if self.images:
            return self.images.first().thumbnail.url
        else:
            return 


class Image(models.Model):
    ice_cream = models.ForeignKey(IceCream, on_delete=models.CASCADE, related_name='images')

    image = ProcessedImageField(
        upload_to='product_images/',
        processors=[ResizeToFill(800, 600)],
        format='JPEG',
        options={'quality': 90}
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 70}
    )

feedback/forms.py
from django import forms
from .models import FeedBack


class FeedBackForm(forms.ModelForm):
    class Meta:
        model = FeedBack
        fields = ['email', 'message']

feedback/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect

from .models import FeedBack
from .forms import FeedBackForm

# Create your views here.
def index(request):
    # return render(request, 'feedback/index.html')

    template = 'feedback/feedback_list.html'
    feedbacks = FeedBack.objects.all() 

    # # только то мороженое, у кторого есть флаг on_main
    context = {
        'feedbacks': feedbacks,
    }
    return render(request, template, context)

def publish_feedback(request):
    context = {
        'created_form': FeedBackForm()
    }

    return render(request, 'feedback/feedback_publish.html', context)


def feedback(request):
    if request.method == 'POST':
        form = FeedBackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.author = request.user
            feedback.save()
            return redirect('feedback:feedback_list')
    else:
        form = FeedBackForm()
    return render(request, 'feedback/feedback_publish.html', {'form': form})

ice_cream/views.py
from django.shortcuts import render

from .models import IceCream


def index(request):
    template = 'ice_cream/index.html'
    selected_ice_creams = IceCream.objects.filter(on_main=True) 

    # только то мороженое, у кторого есть флаг on_main
    context = {
        'selected_ice_creams': selected_ice_creams,
    }
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/ice_cream_list.html'
    ice_creams = IceCream.objects.all()
    # все мороженое
    context = {
        'ice_creams': ice_creams,
    }
    return render(request, template, context)


def ice_cream_detail(request, pk):
    template = 'ice_cream/ice_cream_detail.html'
    ice_cream = IceCream.objects.get(pk=pk)
    # Мороженое с id из запроса
    context = {
        'ice_cream': ice_cream,
    }
    return render(request, template, context)

templates/base.html
{% comment %} загрузка статики {% endcomment %}
{% load static %} 
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-2">
        {% block content %}
          Базовая страница
        {% endblock %}
      </div>
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>    
  </body>
</html>

templates/feedback/feedback_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Отзывы</h1>

<a class="btn btn-success" href="{% url 'feedback:publish_feedback' %}">Написать отзыв</a>

<div class="row py-3">
    {% for feedback in feedbacks %}
      {% include 'feedback/includes/feedback_card.html' %}  
    {% endfor %}
</div>
{% endblock %}

templates/feedback/feedback_publish.html
{% extends 'base.html'%}
{% block content %}
<form action="{% url 'feedback:feedback_success' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{created_form.as_p}}
    <button class="btn btn-success" type="submit">Опубликовать</button>
  </form>
{% endblock %}

templates/feedback/includes/feedback_card.html
{% load static %}

<div class="col-12 col-md-6 col-xl-3 p-3">
  <div class="card h-100">
    <p class="fs-3">{{ feedback.message }}</p>
    <div class="card-body">
      <p class="fs-5">Отзыв от {{ feedback.author }}</p>
    </div> 
  </div>
 </div>

templates/ice_cream/ice_cream_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- py-1: контент внутри блока размещается с отсупом сверху и снизу -->      
<div class="container py-2">
<!-- py-3: контент внутри блока размещается с отсупом сверху и снизу -->
  <div class="row py-3">
  <!-- Блок картинки займет всю ширину родительского блока на мобильном, 
    5/12 на планшете и 1/4 на компьютере -->        
    <div class="col-12 col-md-5 col-xl-3" >
      <!--img-fluid: размер изображения подстроится под занимаемый блок -->
      <!-- img-thumbnail: вокруг изображения тонкая обводка -->
      <img class="img-fluid img-thumbnail" src="{% if ice_cream.get_first_image %}{{ice_cream.get_first_image}}{% else %}{% static 'img/tmb.png' %}{% endif %}" alt="">
      <div class="container px-4 text-center">
        <div class="row gx-5 row-cols-2">
          {% for image in ice_cream.images.all %}
          <div class="col p-2">
            <img src="{{image.thumbnail.url}}" alt="" width="70%">
           </div>
          {% endfor %}

          <!-- <div class="col">
            <div class="p-3">Custom column padding</div>
          </div> -->
        </div>
      </div>

    </div>
    <!-- Блок описания займет всю ширину родительского блока на мобильном, 
       7/12 на планшете и 3/4 на компьютере -->   
    <div class="col-12 col-md-7 col-xl-9">
      <h1>{{ ice_cream.name }}</h1>
      <p>{{ ice_cream.description }}</p>
    </div>
  </div>
</div> 
{% endblock %}

templates/ice_cream/ice_cream_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>Полный список сортов мороженого</h1>
  <!-- py-3: контент внутри блока размещается с отсупом сверху и снизу --> 
  <div class="row py-3">
    {% for ice_cream in ice_creams %}
      {% include 'ice_cream/includes/ice_cream_card.html' %}  
    {% endfor %}
  </div>
{% endblock %}

templates/ice_cream/includes/ice_cream_card.html
{% load static %}

<!-- Блок с карточкой займет всю ширину родительского контейнера на мобильном, 
  половину на планшете и 1/4 на компьютере --> 
<!-- py-3: сделан внутренний отступ, что бы карточки не слипались -->
<div class="col-12 col-md-6 col-xl-3 p-3">
  <!-- h-100:  делает карточки одинаковой высоты -->
  <div class="card h-100">
    <!-- card-img-top: изображение размещается вверху карточки -->
    <!--img-fluid: размер изображения подстроится под занимаемый блок -->
    <img class="card-img-top img-fluid" src="{% if ice_cream.get_first_image %}{{ice_cream.get_first_thumbnail}}{% else %}{% static 'img/tmb.png' %}{% endif %}" alt="">
    <!-- card-body: текстовый контент карточки -->
    <div class="card-body">
      <p class="fs-3">{{ ice_cream.name }}</p>
      <p class="fs-4">{{ ice_cream.price }} UAH</p>
      <p class="fs-5">{{ ice_cream.quantity }} шт.</p>
    </div>
    <!-- btn: показывает что это кнопка  -->
    <!-- btn-success: определяет цвет кнопки --> 
    <a href="{% url 'ice_cream:ice_cream_detail' ice_cream.pk %}" class="btn btn-success">
      Подробная информация
    </a> 
  </div> <!-- Конец карточки -->
 </div> <!-- Конец блока определяющего размер элемента -->

templates/ice_cream/index.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
  <h1>Избранные сорта мороженого</h1>
  <!-- py-3: контент внутри блока размещается с отсупом сверху и снизу --> 
  <div class="row py-3">
    {% for ice_cream in selected_ice_creams %}
      {% include 'ice_cream/includes/ice_cream_card.html' %}  
    {% endfor %}
  </div>
{% endblock %}

templates/includes/footer.html
<p>© 2023 Copyright «Анфиса и друзья»</p> 

templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В качестве обёртки для пунктов меню выступает список  -->
<nav class="navbar navbar-dark navbar-expand-sm" style="background-color: green">
  <div class="container">
    <a class="navbar-brand" href="{% url 'ice_cream:index' %}">
       Анфиса для друзей
    </a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'feedback:feedback_list' %}">
          Отзывы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'ice_cream:ice_cream_list' %}">
          Все сорта мороженого
        </a>
      </li>
    </ul>
  </div>         
</nav>